on:
  push:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - shell: bash
        run: ./gradlew lintDebug
      - if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          path: "*/build/reports/lint-results-debug.html"
  assemble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - shell: bash
        run: ./gradlew android:assembleRelease android:bundleRelease desktop:packageReleaseDeb
      - if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            android/build/outputs/apk/*/release/*-release*.apk
            android/build/outputs/bundle/*Release/*-release*.aab
            desktop/build/compose/binaries/main-release/deb/*.deb
